/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChooseImages: typeof import('./src/views/home/components/ChooseImages.vue')['default']
    Content: typeof import('./src/views/home/components/Content.vue')['default']
    Header: typeof import('./src/views/home/components/Header.vue')['default']
    InputTextEnter: typeof import('./src/components/InputTextEnter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Title: typeof import('./src/views/home/components/Title.vue')['default']
  }
}
